"""Initial Migration

Revision ID: 32c205abae74
Revises: dc7f453a6312
Create Date: 2021-08-21 21:06:07.266491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c205abae74'
down_revision = 'dc7f453a6312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('comment', sa.String(), nullable=False))
    op.add_column('post_like', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'post_like', ['comment'])
    op.drop_column('post_like', 'like')
    op.drop_column('post_like', 'dislike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('dislike', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post_like', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_like', type_='unique')
    op.drop_column('post_like', 'created_at')
    op.drop_column('post_like', 'comment')
    # ### end Alembic commands ###
