"""add pitch table to the database

Revision ID: 578cafa52d09
Revises: e9af2d012c7e
Create Date: 2021-08-19 15:27:37.356112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578cafa52d09'
down_revision = 'e9af2d012c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch')
    # ### end Alembic commands ###
