"""pitch table

Revision ID: 80f99b2069ab
Revises: d54c2db9cbc2
Create Date: 2021-08-19 17:34:00.910066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f99b2069ab'
down_revision = 'd54c2db9cbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitchs_category_key', 'pitchs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pitchs_category_key', 'pitchs', ['category'])
    # ### end Alembic commands ###
