"""Initial Migration

Revision ID: cb050e0accea
Revises: 7c0cb2ab2c83
Create Date: 2021-08-21 21:08:14.673535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb050e0accea'
down_revision = '7c0cb2ab2c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('post_like', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'post_like', ['comment'])
    op.drop_column('post_like', 'like')
    op.drop_column('post_like', 'dislike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('dislike', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post_like', sa.Column('like', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_like', type_='unique')
    op.drop_column('post_like', 'created_at')
    op.drop_column('post_like', 'comment')
    # ### end Alembic commands ###
