"""Initial Migration

Revision ID: dc36068d7ecd
Revises: b783a258fcb5
Create Date: 2021-08-21 02:34:20.515305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc36068d7ecd'
down_revision = 'b783a258fcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('like', sa.Integer(), nullable=False))
    op.add_column('post_like', sa.Column('dislike', sa.Integer(), nullable=False))
    op.add_column('post_like', sa.Column('comment', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'post_like', ['comment'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_like', type_='unique')
    op.drop_column('post_like', 'comment')
    op.drop_column('post_like', 'dislike')
    op.drop_column('post_like', 'like')
    # ### end Alembic commands ###
