"""Initial Migration

Revision ID: dc7f453a6312
Revises: dc36068d7ecd
Create Date: 2021-08-21 02:50:15.494990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7f453a6312'
down_revision = 'dc36068d7ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_like_comment_key', 'post_like', type_='unique')
    op.drop_column('post_like', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('post_like_comment_key', 'post_like', ['comment'])
    # ### end Alembic commands ###
