"""Initial Migration

Revision ID: e9af2d012c7e
Revises: d062b5a2d20c
Create Date: 2021-08-18 12:31:08.457143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9af2d012c7e'
down_revision = 'd062b5a2d20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
