"""Initial Migration

Revision ID: f827cfa91902
Revises: 609ef0e05afe
Create Date: 2021-08-24 01:32:44.712029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f827cfa91902'
down_revision = '609ef0e05afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchs', sa.Column('title', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'pitchs', ['title'])
    op.drop_column('pitchs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchs', sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pitchs', type_='unique')
    op.drop_column('pitchs', 'title')
    # ### end Alembic commands ###
